FinalGene\PhoneBook\AVM\Phonebook:
  xml_root_name: phonebook
  properties:
    name:
      expose: true
      access_type: public_method
      serialized_name: name
      accessor:
        getter: getName
        setter: setName
      xml_attribute: true
      type: string
    owner:
      expose: true
      access_type: public_method
      serialized_name: owner
      accessor:
        getter: getOwner
        setter: setOwner
      xml_attribute: true
      type: integer
    contact:
      expose: true
      access_type: public_method
      serialized_name: contact
      accessor:
        getter: getContact
        setter: setContact
      xml_list:
        inline: true
        entry_name: contact
      type: array<FinalGene\PhoneBook\AVM\Contact>
