FinalGene\PhoneBook\AVM\RealName:
  xml_root_name: realName
  properties:
    __value:
      expose: true
      xml_value: true
      access_type: public_method
      accessor:
        getter: value
        setter: value
      type: string
