FinalGene\PhoneBook\AVM\Telephony:
    xml_root_name: telephony
    properties:
        number:
            expose: true
            access_type: public_method
            serialized_name: number
            xml_element:
                cdata: false
            accessor:
                getter: getNumber
                setter: setNumber
            xml_list:
                inline: true
                entry_name: number
            type: array<FinalGene\PhoneBook\AVM\Number>
