#!/bin/sh

VERSION_TAG=${DOCKER_TAG}

if [ 'latest' == "${VERSION_TAG}" ]; then
    LATEST_RELEASE=$(curl -L -s -H 'Accept: application/json' ${SOURCE_URL%.git}/releases/latest)
    VERSION_TAG=$(echo ${LATEST_RELEASE} | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')
fi

docker build --build-arg VERSION=${VERSION_TAG} -t ${IMAGE_NAME} .
