version: 2.1

jobs:
  build:
    docker:
    - image: finalgene/composer:latest
    working_directory: /tmp/project
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-composer-{{ checksum "composer.lock" }}-{{ checksum ".circleci/config.yml" }}
    - run:
        name: Install composer dependencies
        command: composer install --no-dev --no-interaction --optimize-autoloader --prefer-dist
    - run:
        name: Prepare shared folders
        command: composer run-script install-tools
    - save_cache:
        paths:
        - vendor
        key: v1-composer-{{ checksum "composer.lock" }}-{{ checksum ".circleci/config.yml" }}

  code-style-check:
    docker:
    - image: finalgene/phpcs:latest
    working_directory: /tmp/project
    steps:
    - checkout
    - run:
        name: Execute code style checks
        command: phpcs -p

  unit-tests:
    docker:
    - image: finalgene/php-cli:7.2
    working_directory: /tmp/project
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-composer-{{ checksum "composer.lock" }}-{{ checksum ".circleci/config.yml" }}
    - run:
        name: Execute unit tests
        command: vendor/bin/phpunit --coverage-text --coverage-clover=.build/logs/coverage.clover.xml

    - run:
        name: Upload coverage data
        command: vendor/bin/codacy-coverage clover .build/logs/coverage.clover.xml

  build-phar:
    docker:
    - image: finalgene/box-builder:2.7
    working_directory: /tmp/project
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-composer-{{ checksum "composer.lock" }}-{{ checksum ".circleci/config.yml" }}
    - run:
        name: Build phar
        command: |
          if [ ! -d .build ]; then mkdir .build; fi
          box build
    - persist_to_workspace:
        root: /tmp/project
        paths:
        - .build

  deploy-phar:
    docker:
    - image: circleci/golang:1.9.6
    working_directory: /tmp/project
    steps:
    - checkout
    - run:
        name: Download github-release
        command: go get github.com/aktau/github-release
    - attach_workspace:
        at: /tmp/project
    - run:
        name: Set github username
        command: git config user.name $CIRCLE_PROJECT_USERNAME
    - run:
        name: Deploy phar
        command: github-release upload --user $CIRCLE_PROJECT_USERNAME --repo $CIRCLE_PROJECT_REPONAME --tag $CIRCLE_TAG --name phonebook.phar --file .build/phonebook.phar

workflows:
  version: 2
  build-n-deploy:
    jobs:
    - build:
        filters:
          tags:
            only: /[0-9]+(\.[0-9]+)*/

    - code-style-check:
        requires:
        - build

    - unit-tests:
        requires:
        - build

    - build-phar:
        requires:
        - build
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /[0-9]+(\.[0-9]+)*/

    - deploy-phar:
        requires:
        - build-phar
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /[0-9]+(\.[0-9]+)*/
